### PR TITLE
Remove?: powermanager enhanced error code update

### PR DESCRIPTION
**Pull request by Sumip98**

### CODE REVIEW

**Comment by Ulrond** [comment]
please branch this code directly, I'll add you to the project, remove your fork.

**Review by Ulrond — CHANGES_REQUESTED** [review]
can we delete this review request in preference for -> https://github.com/rdkcentral/rdk-halif-test-power_manager/pull/9

**Review by Ulrond — CHANGES_REQUESTED** [review]
- must be a branch
- please update based on requirements -> https://github.com/rdkcentral/ut-core/discussions/55

**Comment by Sumip98** [comment]
closing pull request as it is duplicate of #9

**Comment by Sumip98** [comment]
closing pull request as it is duplicate of #9

**Pull request closed without merging**
